version: "3.8"

services:
  db:
    build: .
    user: root
    environment:
      - MSSQL_SA_PASSWORD=Hola@1234
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./sql_data:/var/opt/mssql/data